### ISSUE TITLE
OPENUCB-332: /CAS doesn't work the same as /cas

### ISSUE THREAD

**Issue by bwood** [bwood/ucberkeley_cas-7#45]
@Honzi here's a pretty simple one:

> Adding /cas to the end of an Open Berkeley URL in order to log in appears to be case-sensitive.
From email thread with OB client on 6/16/14, 4:16pm:
I was curious as to why Kate was only able to log in to the Procurement site when she clicked on the link I provided in my email, so I checked the link she provided in her first email, which is presumably how she has been attempting to log in:
procurement.berkeley.edu/CAS
Instead of: http://procurement.berkeley.edu/cas
Clicking on the /CAS link (in all uppercase, with or without http://) in a browser where I am not logged in results in me being brought directly back to the home page without successfully logging in. Clicking on the /CAS link in a browser where I am logged in brings me to "Access Denied" page (I remain logged in to the site as normal).

The quick fix is to add an update hook to ucberkeley_cas.install that would create a url alias the same way we create the alias 'caslogout' --> 'user/logout'. This alias would do a 301 redirect of '/CAS' to '/cas'.  I tested that manually in Chrome, FF, Safari and it works fine.

Extra credit:  Why is this path case sensitive?  The answer is probably held in cas.module or phpCAS. Should we consider submitting a patch to https://www.drupal.org/project/cas?

**Comment by honzi** [comment]
I think I've finally figured this one out! I went digging through the cas module files and found that the `cas_menu_site_status_alter` function compares `$path` to `cas`. Since `CAS` does not equal `cas`, the user is not redirected to the front page and gets access denied because of the `user_is_anonymous` access callback on the `cas` menu item. Using PHP's `strtolower` will allow the comparison to work for any capitalization of `cas` and properly redirect the user.

I believe this would be better solved with a patch to the cas module rather than creating potentially lots of extra aliases, but further testing is most likely required.

**Comment by bwood** [comment]
Great!  If you submit a patch, please paste the url to your issue here.  I'll test and hopefully add Drupal's RTBC status.

**Comment by honzi** [comment]
I created the issue. It can be found at https://www.drupal.org/node/2626812 and the patch I made can be found at https://www.drupal.org/files/issues/cas-redirect_nonlowercase_cas_path-2626812-2.patch.

**Comment by bwood** [comment]
Hey, I really appreciate you taking a look at this.  I'm afraid that the change you made to cas does not fix the issue.  I'm going to reply in the drupal.org issue with more detail and submit a patch which (I believe) works.  

I'm thrilled that you are motivated to help us out here.  The CAS module is pretty involved.  I found the correct place (I think!) for the strtolower() function by using phpStorm's XDebug functionality.  I find these tools to be vastly superior to using a basic editor and dpm() or print_r(). What tools are you using for your Drupal development.  If you are interested in using phpStorm and XDebug, let me know and I'll do my best to help you get setup.

**Comment by bwood** [comment]
Here's a patch that will work with our current version (1.3) of cas:
[cas-7.x-1.3-non-lowercase-path-2626812-3.patch.txt](https://github.com/bwood/ucberkeley_cas-7/files/49458/cas-7.x-1.3-non-lowercase-path-2626812-3.patch.txt)

A patch that should work with 1.4 or above is in the above issue.

**Comment by honzi** [comment]
Bah, yeah my patch didn't fully fix all of the issues here, but it fixed the access denied portion which I thought was good enough for its own issue for the CAS module. I think the general redirection one is better separated into a different issue, which I was planning on tackling next. I apologize for not making that clear in my replies to this issue, I get too caught up in the technicals and have much to learn about pacing my responses.

Sure, I'm interested in more ways to test this code, but are there any free alternatives that you would recommend? Or are there some university discounts or other things that make it worth the price?

**Comment by bwood** [comment]
If we get the cas.module patch working we probably won't need to create a url alias (redirection).  So the next think to look at is resolving the [test failures|https://qa.drupal.org/pifr/test/1187053] related to https://www.drupal.org/files/issues/cas-7.x-1.x-non-lowercase-path-2626812-3.patch. I was going to look at this in the next day or two, but if you are familiar with the tests that the cas module is using and you want to jump in let me know. (Or you can move on to https://github.com/bwood/ucberkeley_cas-7/issues/46).


phpStorm is [free for students|https://www.jetbrains.com/student/]. In the past they've given UCB a discount for our use in IST. [You could contact sales|https://www.jetbrains.com/company/contacts/] about that.

In the past I've used Eclipse (free) with XDebug.  It wasn't easy.

It's possible to use XDebug with vim or emacs and both have drupal hook completion modules.  Don't know much about that. 

Apparently [Sublime Text 3 can be used with XDebug|https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=sublime%20xdebug].

**Comment by honzi** [comment]
I will be unable to look at things more closely today due to an appointment, but I believe the failed tests have to do with a typo in the patch you provided: `strotolower` instead of `strtolower`. I'll take a better look at things, including the various editors, tomorrow when I get a chance.

**Comment by bwood** [comment]
Thanks!  The corrected patch passed testing on d.o.  I will roll this into ucberkeley_cas next.  This should be all we need here.

**Comment by honzi** [comment]
I'm glad to help and glad this one turned out well in the end.
